# -*- coding: utf-8 -*-
"""deepleearning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q1Odre9_TI7YpGqLPfy8AKtppCi1Ij89

# **perceptron (binary classification)**
eg:std hrs->pass (1) or fail(0)
"""

import numpy as np

#training data
x=np.array([1,2,3,4]) #stuudy hrs
y=np.array([0,0,1,1]) #pass or fail
x

y

w=0;b=0;lr=1;epochs=5

"""# define activation step **function**"""

def step_function(z) :
  return 1 if z>=0 else 0

#traiing loop
w=0;b=0;lr=1;epochs=5
print("initial weight",w)
print("inital bias",b)
print("learning rate",lr)

for epoch in range(epochs):
  print(f"\n epoch {epoch+1}")
  for i in range(len(x)):
    #1.compute weighted sum
    z=w*x[i]+b
    #2.apply activation function
    y_pred=step_function(z)
    #3.compute error
    err=y[i]-y_pred
    #4.update weigth
    w=w+lr*err*x[i]
    #5.update bias
    b=b+lr*err
    print(f"input {x[i]} ,pred_val {y_pred},actual val :{y[i]},w:{w},b:{b}")

#testing the model
test_val=3.1
z=w*test_val+b
prediction=step_function(z)
print(f"for std hrs {test_val},prediction is {prediction}")

"""# logical **AND**"""

import numpy as np
x1=np.array([0,0,1,1])
x2=np.array([0,1,0,1])
y=np.array([0,0,0,1])

def step_function(z) :
  return 1 if z>=0 else 0



w1=0
w2=0
lr=0.1
b=0
epochs=10
print(f"w1:{w1},w2:{w2},b:{b},epoches:{epochs}")
#traing
for epoch in range(epochs) :
  print("epoch",epoch+1)
  for i in range(len(x1)) :
    #1.compute weighted sum
    z=w1*x1[i]+w2*x2[i]+b
    #2.step function
    y_pred=step_function(z)
    #error
    err=y[i]-y_pred
    #update weight
    w1=w1+lr*err*x1[i]
    w2=w2+lr*err*x2[i]
    #update bias
    b=b+lr*err
    print(f"input x1:{x1[i]} x2:{x2[i]}  y_pred:{y_pred} actual :{y[i]}    w1={w1} w2={w2} b={b}")

#testing dta
x1=0
x2=0
z=w1*x1+w2*x2+b
print(step_function(z))

"""# logical **or**"""

import numpy as np
x1=np.array([0,0,1,1])
x2=np.array([0,1,0,1])
y=np.array([0,1,1,1])
def step_function(z) :
  return 1 if z>=0 else 0
w1=0
w2=0
lr=0.1
b=0
epochs=10
print(f"w1:{w1},w2:{w2},b:{b},epoches:{epochs}")
#traing
for epoch in range(epochs) :
  print("epoch",epoch+1)
  for i in range(len(x1)) :
    #1.compute weighted sum
    z=w1*x1[i]+w2*x2[i]+b
    #2.step function
    y_pred=step_function(z)
    #error
    err=y[i]-y_pred
    #update weight
    w1=w1+lr*err*x1[i]
    w2=w2+lr*err*x2[i]
    #update bias
    b=b+lr*err
    print(f"input x1:{x1[i]} x2:{x2[i]}  y_pred:{y_pred} actual :{y[i]}    w1={w1} w2={w2} b={b}")

import numpy as np
import matplotlib.pyplot as plt

# Input data (OR gate)
x1 = np.array([0, 0, 1, 1])
x2 = np.array([0, 1, 0, 1])
y  = np.array([0, 1, 1, 1])

# Step function
def step_function(z):
    return 1 if z >= 0 else 0

# Initialize weights and bias
w1 = 0.0
w2 = 0.0
b  = 0.0
lr = 0.1
epochs = 10

# Training
for epoch in range(epochs):
    for i in range(len(x1)):
        z = w1 * x1[i] + w2 * x2[i] + b
        y_pred = step_function(z)
        err = y[i] - y_pred

        w1 = w1 + lr * err * x1[i]
        w2 = w2 + lr * err * x2[i]
        b  = b  + lr * err

print("Final weights and bias:")
print("w1 =", w1, "w2 =", w2, "b =", b)

# ---- Plot graph ----
plt.figure()

# Plot points
plt.scatter(x1, x2)
for i in range(len(x1)):
    plt.text(x1[i] + 0.02, x2[i] + 0.02, str(y[i]))

# Decision boundary: w1*x1 + w2*x2 + b = 0
x_vals = np.array([-0.2, 1.2])
y_vals = (-w1 * x_vals - b) / w2

plt.plot(x_vals, y_vals)
plt.xlabel("x1")
plt.ylabel("x2")
plt.title("Perceptron Decision Boundary (OR Gate)")
plt.show()

"""# **xor**"""

import numpy as np
x1=np.array([0,0,1,1])
x2=np.array([0,1,0,1])
y=np.array([0,1,1,0])
def step_function(z) :
  return 1 if z>=0 else 0
w1=0
w2=0
lr=0.5
b=0
epochs=5
print(f"w1:{w1},w2:{w2},b:{b},epoches:{epochs}")
#traing
for epoch in range(epochs) :
  print("epoch",epoch+1)
  for i in range(len(x1)) :
    #1.compute weighted sum
    z=w1*x1[i]+w2*x2[i]+b
    #2.step function
    y_pred=step_function(z)
    #error
    err=y[i]-y_pred
    #update weight
    w1=w1+lr*err*x1[i]
    w2=w2+lr*err*x2[i]
    #update bias
    b=b+lr*err
    print(f"input x1:{x1[i]} x2:{x2[i]}  y_pred:{y_pred} actual :{y[i]}    w1={w1} w2={w2} b={b}")